### ISSUE TITLE
Which branch should we use for a full training?

### ISSUE THREAD

**Issue by SiyuanHuang95** [StanfordVL/bddl#37]
Hi,

I am wondering which branch should we use to have a full set of states' definitions and actions. Since there are plenty of branches right now, I am a slightly confused.

Besides, it seems that bddl currently only contains the init and goal state, how can I obtain the interpolated actions?

Bests,

**Comment by sanjanasrivastava** [comment]
Hi,

Right now, `develop` would be the best branch for sourcing definitions. However do note that they are subject to minor changes in the coming couple weeks.

BDDL does not have defined actions, but many people have worked on making actions themselves! 

Thanks,
Sanjana

**Comment by SiyuanHuang95** [comment]
Hi,

thanks for your quick reply! Really appreciate it.

Would it be possible to give some recommendations w.r.t the actions making? Also, I am curious that if BDDL only defines the init and goal states, how come to the replyed trajectories in the simulator, like iGibson? I am a newbie, forgive me if dummy any questions.

**Comment by sanjanasrivastava** [comment]
Hi Siyuan, 

I haven't worked on actions before, but one of my colleagues will answer later today.

Yes - the goals are defined. The "solver" mentioned in the readme actually isn't a planning solver, it's a (rough) logic solver for the goal expressions. So it solves the goal expressions (which include logic operators like quantifiers, disjunction/conjunction, implication, etc.) by identifying ground solutions (just a set of literals). However, these are still just states that satisfy the goal - they don't have anything to do with getting from the init to the goal.

**Comment by SiyuanHuang95** [comment]
Hi Sanjana,

thanks for your feedback! 

For the actions, yes, I will wait for your colleague's update!

For BDDL, so it more focused on the init-goal state descriptions? And use that to evaluate the trajectory/behivaour generated?

**Comment by cgokmen** [comment]
Hi @SiyuanHuang95,

BDDL is used to define tasks that are meant to be solved in a simulation environment (iGibson / OmniGibson). These task definitions only specify initial and goal conditions, and there is no planning-level actions provided in a PDDL sense because it is not possible to concretely identify the preconditions and postconditions of actions that a robot can take in the environment (especially since the action space is low-level continuous joint control).

The task definitions are used to both instantiate tasks (e.g. set a scene up such that it is aligned with the task's starting state) and for checking if the task has been completed (simulator provides physical implementations of each of the predicates). They are _not_ used to execute a task: if there are high-level actions needed to solve the tasks, they are up to the user to define. As you correctly identified, BEHAVIOR-1K is a benchmark (e.g. you can use it to evaluate an agent) and a simulation platform (e.g. you can use it to generate your own training data) but so far we do not provide the training data directly - that's up to you to decide how to do.

To that end, we do have some ongoing efforts involving collecting VR demonstrations of task completion (these are already available for our earlier project BEHAVIOR-100) and a set of basic primitive actions (e.g. actions at the "Grasp", "Open", "Place" level rather than joint control). These will be gradually released in the upcoming months so I invite you to check back if you are interested.

Thanks,
Cem

**Comment by SiyuanHuang95** [comment]
Hi @cgokmen,

Great thanks for your reply.

For BDDL and simulator parts: Clear, thanks for your useful info.

For dataset: Great, that's really what I need actually. I am more interested in mid-level actions, like compound actions to finish a task with pre-defined action primitives. 

So, please do inform me when there is a big update!

Bests,
